//**********************************************************************************************************************************
//LICENSING
// Copyright(C) 2021, 2025  TG Team,Key Laboratory of Jiangsu province High-Tech design of wind turbine,WTG,WL,赵子祯
//
//    This file is part of HawtC3 and  auto generated by python script by WL,赵子祯
//
// Licensed under the Boost Software License - Version 1.0 - August 17th, 2003
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.HawtC.cn/licenses.txt
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// 
//**********************************************************************************************************************************

#pragma once
#ifndef LOGINTERFACES_H
#define LOGINTERFACES_H





#include <string>
#include <memory>

namespace HawtC3 {
	namespace IO {
		namespace Log {

			/// <summary>
			/// 输出文件接口
			/// </summary>

			/// <summary>
			/// VTK基础类
			/// </summary>
			class BASE_VTK {
			public:
				virtual ~BASE_VTK() = default;

				/// <summary>
				/// 关闭VTK输出
				/// </summary>
				virtual void OutVTKClose() = 0;
			};

			/// <summary>
			/// 邮件类
			/// </summary>
			class Email {
			public:
				virtual ~Email() = default;

				/// <summary>
				/// 发送邮件
				/// </summary>
				/// <param name="subject">邮件主题</param>
				/// <param name="body">邮件内容</param>
				/// <param name="to">收件人</param>
				virtual void SendEmail(const std::string& subject, const std::string& body, const std::string& to) = 0;
			};

		} // namespace Log
	} // namespace IO
} // namespace HawtC3
#endif // !LOGINTERFACES_H